### PR TITLE
Adding ppc64le build support for docker-in-docker

### PR DESCRIPTION
**Pull request by Pensu**
**What this PR does / why we need it**:
This will help make docker-in-docker on ppc64le.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Specify your PR reviewers**:

/cc @gyliu513 @morvencao @clyang82

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mkumatag** [comment]
@morvencao I'm wondering if someone can help us build and push this image for ppc64le architecture

**Comment by morvencao** [comment]
@mkumatag I will try to build the image for ppc64le arch.

**Comment by morvencao** [comment]
Forget we have prow job to build the image, see: https://github.com/IBM/test-infra/blob/master/prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
But we current just have cover amd64 platfrom, this is building log:
http://prow.purple-chesterfield.com/?repo=IBM%2Ftest-infra&type=postsubmit

**Comment by morvencao** [comment]
I encounter some issue to start the docker daemon after I build the image on power:

```
# docker run -it quay.io/multicloudlab/multicloudlab-builder-ppc64le:v20200121-7bde163b4 bash
+ service docker start
 * Starting Docker: docker                                                                                                                                                                                                           [ OK ]
+ exec bash
root@2d9aa83de123:/# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:26:10 2018
 OS/Arch:           linux/ppc64le
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

@Pensu PTAL

**Comment by Pensu** [comment]
@morvencao It looks like the error is because we are not mounting the docker socket inside the image. I had the same error while I try to run the `v20200120-9057596` tagged image from: https://quay.io/repository/multicloudlab/multicloudlab-builder?tab=tags on x86 platform. Here is the result:

```
# docker run -it quay.io/multicloudlab/multicloudlab-builder:v20200120-9057596 bash
Unable to find image 'quay.io/multicloudlab/multicloudlab-builder:v20200120-9057596' locally
v20200120-9057596: Pulling from multicloudlab/multicloudlab-builder
0a01a72a686c: Already exists
cc899a5544da: Already exists
19197c550755: Already exists
716d454e56b6: Already exists
61380e7c25b5: Pull complete
129f8bd353df: Pull complete
15ac857f13c6: Pull complete
7affef717700: Pull complete
2d50aee0f1eb: Pull complete
Digest: sha256:1a95c8878b545ef8157c7412c02aae2bb4df7fd8d0d30e936f17f6540efab86b
Status: Downloaded newer image for quay.io/multicloudlab/multicloudlab-builder:v20200120-9057596
+ service docker start
 * Starting Docker: docker                                                                                                                                                    [ OK ]
+ exec bash
root@28d59e561390:/# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@28d59e561390:/#
```

I think here we expecting the yaml which will make use of this image to mount the docker socket. Otherwise we need to mount /var/run/docker.sock in the image itself. 

Can you help me understand if the behaviour on x86, that I pasted above, is incorrect or expected?

**Comment by morvencao** [comment]
Yes, it is.
Thanks @Pensu
Anyway, now it's time to have a try on a ppc64le cluster to see if it is working.

**Comment by mkumatag** [comment]
I'm wondering if we can migrate to use tools like buildah which does not need any docker daemon for building the container images!

**Comment by morvencao** [comment]
It worths a try, we also considered to use [dind](https://github.com/jpetazzo/dind)
With the evolution of this repo, we should introduce more awesome tools..

**Pull request merged**
